# BEGIN_KITTY_THEME
# One Dark
include current-theme.conf
# END_KITTY_THEME

font_family  FiraCode

font_size 15 

adjust_line_height 175%

cursor_blink_interval 0

enable_audio_bell no

#hide_window_decorations yes

window_padding_width 12
